import fs from 'node:fs';
import path from 'node:path';
import type { TimeEntry, PaperclipSyncPayload } from '../shared/types.js';

/**
 * Sync time entries to the Paperclip vault.
 * Writes a markdown report into the Paperclip vault under
 * vault/communications/time-reports/{memberId}-{month}.md
 */
export async function syncToPaperclip(
  memberId: string,
  paperclipPath: string,
  entries: TimeEntry[],
  month: string
): Promise<{ success: boolean; message: string }> {
  try {
    const vaultDir = path.join(paperclipPath, 'vault', 'communications', 'time-reports');
    if (!fs.existsSync(vaultDir)) {
      fs.mkdirSync(vaultDir, { recursive: true });
    }

    if (!/^\d{4}-\d{2}$/.test(month)) {
      return { success: false, message: `Invalid month format: ${month} (expected YYYY-MM)` };
    }
    const safeMemberId = memberId.replace(/[^A-Za-z0-9_-]/g, '_');
    const fileName = `${safeMemberId}-${month}.md`;
    const filePath = path.join(vaultDir, fileName);

    const totalSeconds = entries.reduce((s, e) => s + e.durationSeconds, 0);
    const billableSeconds = entries.filter(e => e.billable).reduce((s, e) => s + e.durationSeconds, 0);

    const lines = [
      `# Time Report — ${month}`,
      ``,
      `- **Member:** ${memberId}`,
      `- **Generated:** ${new Date().toISOString()}`,
      `- **Total Time:** ${formatDuration(totalSeconds)}`,
      `- **Billable:** ${formatDuration(billableSeconds)}`,
      `- **Entries:** ${entries.length}`,
      ``,
      `## Entries`,
      ``,
      `| Date | Project | Description | Duration | Billable |`,
      `|------|---------|-------------|----------|----------|`,
    ];

    const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
    for (const e of entries) {
      const date = new Date(e.startTime).toISOString().slice(0, 10);
      lines.push(`| ${date} | ${cell(e.projectId)} | ${cell(e.description)} | ${formatDuration(e.durationSeconds)} | ${e.billable ? 'Yes' : 'No'} |`);
    }

    lines.push(``, `---`, `> Auto-generated by Plexus Time Tracker`);

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');

    return { success: true, message: `Wrote ${entries.length} entries to ${filePath}` };
  } catch (err: any) {
    return { success: false, message: err.message };
  }
}

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  return `${h}h ${m}m`;
}
