#!/usr/bin/env node
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => readFileSync(path.join(root, file), 'utf8');
const catalog = 'docs/DOCUMENTATION_CATALOG.md';
const policy = JSON.parse(read('docs/documentation-policy.json'));
const args = process.argv.slice(2);
if (args.some(arg => !['--write', '--report'].includes(arg))) {
  throw new Error('Usage: node scripts/verify-docs.mjs [--write] [--report]');
}
const files = [...new Set(execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
  cwd: root, encoding: 'utf8',
}).split('\0').filter(file => /\.(?:md|mdx|html)$/.test(file)).concat(catalog))].sort();

function classify(file) {
  if (policy.current.includes(file)) return 'Current guidance';
  for (const rule of policy.routes) {
    if (new RegExp(rule.pattern).test(file)) return rule.role;
  }
  return 'Unclassified';
}

const rows = files.map(file => ({ file, role: classify(file) }));
const groups = [...new Set(rows.map(row => row.role))].sort();
const link = file => encodeURI(path.posix.relative('docs', file));
const generated = [
  '# Repository documentation catalog', '',
  'Generated by `npm run docs:refresh`; verify with `npm run verify:docs`.',
  'Roles describe authority, not completion. Dated plans and receipts are not current execution instructions.',
  'Read [the documentation map](DOCUMENTATION_MAP.md) for source and acceptance ownership.', '',
  `Catalog coverage: **${rows.length} Markdown/MDX/HTML documents**. Structured planning JSON is checked separately.`, '',
  ...groups.flatMap(role => [
    `## ${role}`, '', '| Document |', '| --- |',
    ...rows.filter(row => row.role === role).map(row => `| [${row.file}](${link(row.file)}) |`), '',
  ]),
].join('\n');
if (args.includes('--write')) writeFileSync(path.join(root, catalog), generated);

const errors = [];
if (!existsSync(path.join(root, catalog)) || read(catalog) !== generated) {
  errors.push('Documentation catalog is stale. Run npm run docs:refresh.');
}
for (const { file, role } of rows) if (role === 'Unclassified') errors.push(`Unclassified document: ${file}`);
for (const file of policy.current) if (!files.includes(file)) errors.push(`Current policy target missing: ${file}`);

function localLinks(body) {
  const prose = body.replace(/^(`{3,}|~{3,})[^\n]*\n[\s\S]*?^\1\s*$/gm, '');
  return [
    ...prose.matchAll(/!?\[[^\]]*\]\((<[^>]+>|[^\s)]+)(?:\s+["'][^)]*)?\)/g),
    ...prose.matchAll(/^\s*\[[^\]]+\]:\s*(<[^>]+>|\S+)/gm),
  ].map(match => match[1].replace(/^<|>$/g, ''));
}

const historicalMissing = [];
for (const { file, role } of rows) {
  if (!existsSync(path.join(root, file))) { errors.push(`Document missing: ${file}`); continue; }
  if (file.endsWith('.html')) continue; // Visual reference HTML is inventoried, not treated as Markdown.
  for (const href of localLinks(read(file))) {
    if (/^(?:[a-z][a-z\d+.-]*:|#|\/\/)/i.test(href)) continue;
    const target = decodeURIComponent(href.split(/[?#]/)[0]);
    if (!target) continue;
    const resolved = path.resolve(root, path.dirname(file), target);
    const outside = !resolved.startsWith(`${root}${path.sep}`) && resolved !== root;
    if (outside || !existsSync(resolved)) {
      const message = `${file}: ${outside ? 'non-portable' : 'missing'} local target ${target}`;
      if (['Current guidance', 'Contributor reference'].includes(role)) errors.push(message);
      else historicalMissing.push(message);
    }
  }
}

const pkg = JSON.parse(read('package.json'));
const lock = JSON.parse(read('package-lock.json'));
if (pkg.version !== lock.version || pkg.version !== lock.packages?.['']?.version) {
  errors.push('Package and lock versions diverge.');
}
const feed = read('src/main/updates.ts').match(/const DEFAULT_FEED_URL = '([^']+)'/)?.[1];
if (!feed || pkg.build?.publish?.[0]?.url !== feed) errors.push('Runtime and packaging feed pins diverge.');
const ota = read('docs/OTA_RELEASE.md');
const documentedFeed = ota.match(/^## Runtime Feed\s*\n(?:(?!^## )[\s\S])*?^```[^\n]*\n([^\n]+)\n```/m)?.[1];
if (!feed || documentedFeed !== feed) errors.push('OTA runbook must show the exact current source feed.');

const isa = read('ISA.md');
const criteria = [...isa.matchAll(/^- \[([ x])\] ISC-([\d.]+):/gm)];
const passed = criteria.filter(match => match[1] === 'x').length;
if (!criteria.length) errors.push('ISA must contain acceptance criteria.');
if (new Set(criteria.map(match => match[2])).size !== criteria.length) errors.push('ISA criterion IDs are duplicated.');
if (isa.match(/^progress: (.*)$/m)?.[1] !== `${passed}/${criteria.length}`) errors.push('ISA progress does not match its checklist.');
const state = read('.planning/STATE.md');
const phases = [...state.matchAll(/^Phase: (.+)$/gm)];
const next = JSON.parse(read('.planning/NEXT-WAVE.json'));
if (phases.length !== 1 || !phases[0][1].startsWith(`${next.current_phase}-`)) {
  errors.push('STATE must name one current phase matching NEXT-WAVE.');
}
const requiredScripts = {
  'verify:docs': 'node scripts/verify-docs.mjs',
  'docs:refresh': 'node scripts/verify-docs.mjs --write',
  'test:release-ops': 'node --test scripts/cleanup-r2.test.mjs',
  'test:docs': 'node --test scripts/verify-docs.test.mjs',
};
for (const [name, command] of Object.entries(requiredScripts)) {
  if (pkg.scripts?.[name] !== command) errors.push(`Package script ${name} must invoke ${command}.`);
}
// These required steps deliberately use standalone literal run scalars.
// Fail closed if refactored into block scalars until this contract is updated.
const ciRuns = [...read('.github/workflows/ci.yml').matchAll(/^ +(?:- )?run: (npm run [\w:-]+)\s*$/gm)].map(match => match[1]);
for (const command of ['npm run verify:docs', 'npm run test:release-ops', 'npm run test:docs']) {
  if (!ciRuns.includes(command)) errors.push(`CI must run ${command} in a standalone run step.`);
}

const report = {
  documents: rows.length,
  roles: Object.fromEntries(groups.map(role => [role, rows.filter(row => row.role === role).length])),
  currentLocalLinkErrors: errors.filter(error => /local target/.test(error)),
  historicalMissingLocalReferences: [...new Set(historicalMissing)].sort(),
  isa: { passed, total: criteria.length },
  errors,
};
if (args.includes('--report')) console.log(JSON.stringify(report, null, 2));
else {
  console.log(`[verify:docs] ${rows.length} documents; ISA ${passed}/${criteria.length}; ${errors.length} error(s).`);
  console.log(`[verify:docs] ${report.historicalMissingLocalReferences.length} historical/reference link limitation(s); use --report for paths.`);
  for (const error of errors) console.error(`[verify:docs] ${error}`);
}
if (errors.length) process.exitCode = 1;
